export const COUNTRIES = [
  { code: "MG", name: "Madagascar", flag: "🇲🇬", capital: "Antananarivo" },
  { code: "FR", name: "France", flag: "🇫🇷", capital: "Paris" },
  { code: "DE", name: "Allemagne", flag: "🇩🇪", capital: "Berlin" },
  { code: "US", name: "États-Unis", flag: "🇺🇸", capital: "Washington" },
  { code: "GB", name: "Royaume-Uni", flag: "🇬🇧", capital: "Londres" },
  { code: "CA", name: "Canada", flag: "🇨🇦", capital: "Ottawa" },
  { code: "BE", name: "Belgique", flag: "🇧🇪", capital: "Bruxelles" },
  { code: "CH", name: "Suisse", flag: "🇨🇭", capital: "Berne" },
  { code: "IT", name: "Italie", flag: "🇮🇹", capital: "Rome" },
  { code: "ES", name: "Espagne", flag: "🇪🇸", capital: "Madrid" },
  { code: "PT", name: "Portugal", flag: "🇵🇹", capital: "Lisbonne" },
  { code: "BR", name: "Brésil", flag: "🇧🇷", capital: "Brasília" },
  { code: "AR", name: "Argentine", flag: "🇦🇷", capital: "Buenos Aires" },
  { code: "MX", name: "Mexique", flag: "🇲🇽", capital: "Mexico" },
  { code: "JP", name: "Japon", flag: "🇯🇵", capital: "Tokyo" },
  { code: "CN", name: "Chine", flag: "🇨🇳", capital: "Pékin" },
  { code: "IN", name: "Inde", flag: "🇮🇳", capital: "New Delhi" },
  { code: "RU", name: "Russie", flag: "🇷🇺", capital: "Moscou" },
  { code: "AU", name: "Australie", flag: "🇦🇺", capital: "Canberra" },
  { code: "ZA", name: "Afrique du Sud", flag: "🇿🇦", capital: "Pretoria" },
  { code: "NG", name: "Nigeria", flag: "🇳🇬", capital: "Abuja" },
  { code: "KE", name: "Kenya", flag: "🇰🇪", capital: "Nairobi" },
  { code: "SN", name: "Sénégal", flag: "🇸🇳", capital: "Dakar" },
  { code: "CI", name: "Côte d'Ivoire", flag: "🇨🇮", capital: "Yamoussoukro" },
  { code: "CM", name: "Cameroun", flag: "🇨🇲", capital: "Yaoundé" },
  { code: "MA", name: "Maroc", flag: "🇲🇦", capital: "Rabat" },
  { code: "TN", name: "Tunisie", flag: "🇹🇳", capital: "Tunis" },
  { code: "DZ", name: "Algérie", flag: "🇩🇿", capital: "Alger" },
  { code: "EG", name: "Égypte", flag: "🇪🇬", capital: "Le Caire" },
  { code: "GH", name: "Ghana", flag: "🇬🇭", capital: "Accra" },
  { code: "TZ", name: "Tanzanie", flag: "🇹🇿", capital: "Dodoma" },
  { code: "UG", name: "Ouganda", flag: "🇺🇬", capital: "Kampala" },
  { code: "CD", name: "RD Congo", flag: "🇨🇩", capital: "Kinshasa" },
  { code: "CG", name: "Congo", flag: "🇨🇬", capital: "Brazzaville" },
  { code: "GA", name: "Gabon", flag: "🇬🇦", capital: "Libreville" },
  { code: "ML", name: "Mali", flag: "🇲🇱", capital: "Bamako" },
  { code: "BF", name: "Burkina Faso", flag: "🇧🇫", capital: "Ouagadougou" },
  { code: "NE", name: "Niger", flag: "🇳🇪", capital: "Niamey" },
  { code: "TD", name: "Tchad", flag: "🇹🇩", capital: "N'Djamena" },
  { code: "RW", name: "Rwanda", flag: "🇷🇼", capital: "Kigali" },
  { code: "MU", name: "Maurice", flag: "🇲🇺", capital: "Port-Louis" },
  { code: "SC", name: "Seychelles", flag: "🇸🇨", capital: "Victoria" },
  { code: "KM", name: "Comores", flag: "🇰🇲", capital: "Moroni" },
];
